namespace SJRAtlas.CGNS
{
}
namespace SJRAtlas.CGNS
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.832
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "SearchResults")]
    public partial class GnssSearchResults
    {
        private GnssPlaceName[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlaceName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GnssPlaceName[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        public string ToXml()
        {
            System.IO.StringWriter writer = new System.IO.StringWriter();
            Serializer.Serialize(writer, this);
            string xml = writer.ToString();
            writer.Close();
            return xml;
        }

        public static GnssSearchResults CreateFromXml(System.IO.Stream stream)
        {
            return (GnssSearchResults)Serializer.Deserialize(stream);
        }

        private static XmlSerializer Serializer
        {
            get
            {
                if (serializer == null)
                    serializer = new XmlSerializer(typeof(GnssSearchResults));

                return serializer;
            }
        }

        private static XmlSerializer serializer;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRoot("PlaceName")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class GnssPlaceName
    {

        private string geonameField;

        private string status_termField;

        private string latitudeField;

        private string longitudeField;

        private string latdecField;

        private string londecField;

        private string coord_acc_mField;

        private string concise_termField;

        private string generic_termField;

        private string region_nameField;

        private string nts_mapField;

        private string datumField;

        private string cgndb_keyField;

        private string feature_idField;

        private string concise_typeField;

        private string locationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string geoname
        {
            get
            {
                return this.geonameField;
            }
            set
            {
                this.geonameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status_term
        {
            get
            {
                return this.status_termField;
            }
            set
            {
                this.status_termField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string latdec
        {
            get
            {
                return this.latdecField;
            }
            set
            {
                this.latdecField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string londec
        {
            get
            {
                return this.londecField;
            }
            set
            {
                this.londecField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coord_acc_m
        {
            get
            {
                return this.coord_acc_mField;
            }
            set
            {
                this.coord_acc_mField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string concise_term
        {
            get
            {
                return this.concise_termField;
            }
            set
            {
                this.concise_termField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string generic_term
        {
            get
            {
                return this.generic_termField;
            }
            set
            {
                this.generic_termField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string region_name
        {
            get
            {
                return this.region_nameField;
            }
            set
            {
                this.region_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nts_map
        {
            get
            {
                return this.nts_mapField;
            }
            set
            {
                this.nts_mapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cgndb_key
        {
            get
            {
                return this.cgndb_keyField;
            }
            set
            {
                this.cgndb_keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string feature_id
        {
            get
            {
                return this.feature_idField;
            }
            set
            {
                this.feature_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string concise_type
        {
            get
            {
                return this.concise_typeField;
            }
            set
            {
                this.concise_typeField = value;
            }
        }
    }
}

public partial class SearchResults {
}
