//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJRAtlas.Site.Models {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("errors", Schema="dbo")]
    public partial class Error : ActiveRecordBase<Error> {
        
        private string _message;
        
        private string _stackTrace;
        
        private string _source;
        
        private int _parentId;
        
        private int _id;
        
        [Property("message", ColumnType="StringClob")]
        public virtual string Message {
            get {
                return this._message;
            }
            set {
                this._message = value;
            }
        }
        
        [Property("stacktrace", ColumnType="StringClob")]
        public virtual string StackTrace {
            get {
                return this._stackTrace;
            }
            set {
                this._stackTrace = value;
            }
        }
        
        [Property("source", ColumnType="StringClob")]
        public virtual string Source {
            get {
                return this._source;
            }
            set {
                this._source = value;
            }
        }
        
        [Property("parent_exception", ColumnType="Int32")]
        public virtual int ParentId {
            get {
                return this._parentId;
            }
            set {
                this._parentId = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Increment, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
    }
}
