//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJRAtlas.Models.Atlas {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("web_map_services", Schema="dbo")]
    public partial class MapService : ActiveRecordBase<MapService> {
        
        private string _displayName;
        
        private string _serviceName;
        
        private bool _visible;
        
        private int _id;
        
        private IList<MapServiceListing> _mapServiceListings;
        
        [Property("display_name", ColumnType="String", NotNull=true)]
        public virtual string DisplayName {
            get {
                return this._displayName;
            }
            set {
                this._displayName = value;
            }
        }
        
        [Property("service_name", ColumnType="String", NotNull=true)]
        public virtual string ServiceName {
            get {
                return this._serviceName;
            }
            set {
                this._serviceName = value;
            }
        }
        
        [Property("visible", ColumnType="Boolean", NotNull=true)]
        public virtual bool Visible {
            get {
                return this._visible;
            }
            set {
                this._visible = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [HasMany(typeof(MapServiceListing))]
        public virtual IList<MapServiceListing> MapServiceListings {
            get {
                return this._mapServiceListings;
            }
            set {
                this._mapServiceListings = value;
            }
        }
    }
    
    [ActiveRecord("web_map_service_listings", Schema="dbo")]
    public partial class MapServiceListing : ActiveRecordBase<MapServiceListing> {
        
        private int _interactiveMapId;
        
        private int _mapServiceId;
        
        private int _position;
        
        private int _id;
        
        private InteractiveMap _interactiveMap;
        
        private MapService _mapService;
        
        [Property("interactive_map_id", ColumnType="Int32", NotNull=true)]
        public virtual int InteractiveMapId {
            get {
                return this._interactiveMapId;
            }
            set {
                this._interactiveMapId = value;
            }
        }
        
        [Property("map_service_id", ColumnType="Int32", NotNull=true)]
        public virtual int MapServiceId {
            get {
                return this._mapServiceId;
            }
            set {
                this._mapServiceId = value;
            }
        }
        
        [Property("position", ColumnType="Int32", NotNull=true)]
        public virtual int Position {
            get {
                return this._position;
            }
            set {
                this._position = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [BelongsTo("interactive_map_id", NotNull=false)]
        public virtual InteractiveMap InteractiveMap {
            get {
                return this._interactiveMap;
            }
            set {
                this._interactiveMap = value;
            }
        }
        
        [BelongsTo("map_service_id", NotNull=false)]
        public virtual MapService MapService {
            get {
                return this._mapService;
            }
            set {
                this._mapService = value;
            }
        }
    }
    
    [ActiveRecord("web_interactive_maps", Schema="dbo")]
    public partial class InteractiveMap : ActiveRecordBase<InteractiveMap> {
        
        private string _title;
        
        private string _abstract;
        
        private string _origin;
        
        private string _timePeriod;
        
        private bool _isBasinMap;
        
        private string _thumbnailUrl;
        
        private string _largeThumbnailUrl;
        
        private System.DateTime _createdAt;
        
        private System.DateTime _updatedAt;
        
        private int _id;
        
        private int _overviewMapServiceId;
        
        private IList<MapServiceListing> _mapServiceListings;
        
        [Property("title", ColumnType="String", NotNull=true)]
        public virtual string Title {
            get {
                return this._title;
            }
            set {
                this._title = value;
            }
        }
        
        [Property("abstract", ColumnType="StringClob")]
        public virtual string Abstract {
            get {
                return this._abstract;
            }
            set {
                this._abstract = value;
            }
        }
        
        [Property("origin", ColumnType="String")]
        public virtual string Origin {
            get {
                return this._origin;
            }
            set {
                this._origin = value;
            }
        }
        
        [Property("time_period", ColumnType="String")]
        public virtual string TimePeriod {
            get {
                return this._timePeriod;
            }
            set {
                this._timePeriod = value;
            }
        }
        
        [Property("full_basin_coverage", ColumnType="Boolean", NotNull=true)]
        public virtual bool IsBasinMap {
            get {
                return this._isBasinMap;
            }
            set {
                this._isBasinMap = value;
            }
        }
        
        [Property("thumbnail_url", ColumnType="String")]
        public virtual string ThumbnailUrl {
            get {
                return this._thumbnailUrl;
            }
            set {
                this._thumbnailUrl = value;
            }
        }
        
        [Property("large_thumbnail_url", ColumnType="String")]
        public virtual string LargeThumbnailUrl {
            get {
                return this._largeThumbnailUrl;
            }
            set {
                this._largeThumbnailUrl = value;
            }
        }
        
        [Property("created_at", ColumnType="Timestamp")]
        public virtual System.DateTime CreatedAt {
            get {
                return this._createdAt;
            }
            set {
                this._createdAt = value;
            }
        }
        
        [Property("updated_at", ColumnType="Timestamp")]
        public virtual System.DateTime UpdatedAt {
            get {
                return this._updatedAt;
            }
            set {
                this._updatedAt = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Native, "id", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("overview_map_service_id", ColumnType="Int32")]
        public virtual int OverviewMapServiceId {
            get {
                return this._overviewMapServiceId;
            }
            set {
                this._overviewMapServiceId = value;
            }
        }
        
        [HasMany(typeof(MapServiceListing), OrderBy="position")]
        public virtual IList<MapServiceListing> MapServiceListings {
            get {
                return this._mapServiceListings;
            }
            set {
                this._mapServiceListings = value;
            }
        }
    }
}
