//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJRAtlas.Models.DataWarehouse {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("tblAquaticSite", Schema="dbo")]
    public partial class AquaticSite : ActiveRecordBase<AquaticSite> {
        
        private int _id;
        
        private int _oldAquaticSiteID;
        
        private short _riverSystemID;
        
        private int _waterBodyID;
        
        private string _waterBodyName;
        
        private string _aquaticSiteName;
        
        private string _aquaticSiteDesc;
        
        private string _habitatDesc;
        
        private int _reachNo;
        
        private string _startDesc;
        
        private string _endDesc;
        
        private double _startRouteMeas;
        
        private double _endRouteMeas;
        
        private string _siteType;
        
        private string _specificSiteInd;
        
        private string _geoReferencedInd;
        
        private bool _incorporatedInd;
        
        private string _coordinateSource;
        
        private string _coordinateSystem;
        
        private string _xCoordinate;
        
        private string _yCoordinate;
        
        private string _coordinateUnits;
        
        private string _comments;
        
        [PrimaryKey(PrimaryKeyType.Native, "AquaticSiteID", ColumnType="Int32")]
        public virtual int Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("oldAquaticSiteID", ColumnType="Int32")]
        public virtual int OldAquaticSiteID {
            get {
                return this._oldAquaticSiteID;
            }
            set {
                this._oldAquaticSiteID = value;
            }
        }
        
        [Property("RiverSystemID", ColumnType="Int16")]
        public virtual short RiverSystemID {
            get {
                return this._riverSystemID;
            }
            set {
                this._riverSystemID = value;
            }
        }
        
        [Property("WaterBodyID", ColumnType="Int32")]
        public virtual int WaterBodyID {
            get {
                return this._waterBodyID;
            }
            set {
                this._waterBodyID = value;
            }
        }
        
        [Property("WaterBodyName", ColumnType="String")]
        public virtual string WaterBodyName {
            get {
                return this._waterBodyName;
            }
            set {
                this._waterBodyName = value;
            }
        }
        
        [Property("AquaticSiteName", ColumnType="String")]
        public virtual string AquaticSiteName {
            get {
                return this._aquaticSiteName;
            }
            set {
                this._aquaticSiteName = value;
            }
        }
        
        [Property("AquaticSiteDesc", ColumnType="String")]
        public virtual string AquaticSiteDesc {
            get {
                return this._aquaticSiteDesc;
            }
            set {
                this._aquaticSiteDesc = value;
            }
        }
        
        [Property("HabitatDesc", ColumnType="String")]
        public virtual string HabitatDesc {
            get {
                return this._habitatDesc;
            }
            set {
                this._habitatDesc = value;
            }
        }
        
        [Property("ReachNo", ColumnType="Int32")]
        public virtual int ReachNo {
            get {
                return this._reachNo;
            }
            set {
                this._reachNo = value;
            }
        }
        
        [Property("StartDesc", ColumnType="String")]
        public virtual string StartDesc {
            get {
                return this._startDesc;
            }
            set {
                this._startDesc = value;
            }
        }
        
        [Property("EndDesc", ColumnType="String")]
        public virtual string EndDesc {
            get {
                return this._endDesc;
            }
            set {
                this._endDesc = value;
            }
        }
        
        [Property("StartRouteMeas", ColumnType="Double")]
        public virtual double StartRouteMeas {
            get {
                return this._startRouteMeas;
            }
            set {
                this._startRouteMeas = value;
            }
        }
        
        [Property("EndRouteMeas", ColumnType="Double")]
        public virtual double EndRouteMeas {
            get {
                return this._endRouteMeas;
            }
            set {
                this._endRouteMeas = value;
            }
        }
        
        [Property("SiteType", ColumnType="String")]
        public virtual string SiteType {
            get {
                return this._siteType;
            }
            set {
                this._siteType = value;
            }
        }
        
        [Property("SpecificSiteInd", ColumnType="String")]
        public virtual string SpecificSiteInd {
            get {
                return this._specificSiteInd;
            }
            set {
                this._specificSiteInd = value;
            }
        }
        
        [Property("GeoReferencedInd", ColumnType="String")]
        public virtual string GeoReferencedInd {
            get {
                return this._geoReferencedInd;
            }
            set {
                this._geoReferencedInd = value;
            }
        }
        
        [Property("IncorporatedInd", ColumnType="Boolean")]
        public virtual bool IncorporatedInd {
            get {
                return this._incorporatedInd;
            }
            set {
                this._incorporatedInd = value;
            }
        }
        
        [Property("CoordinateSource", ColumnType="String")]
        public virtual string CoordinateSource {
            get {
                return this._coordinateSource;
            }
            set {
                this._coordinateSource = value;
            }
        }
        
        [Property("CoordinateSystem", ColumnType="String")]
        public virtual string CoordinateSystem {
            get {
                return this._coordinateSystem;
            }
            set {
                this._coordinateSystem = value;
            }
        }
        
        [Property("XCoordinate", ColumnType="String")]
        public virtual string XCoordinate {
            get {
                return this._xCoordinate;
            }
            set {
                this._xCoordinate = value;
            }
        }
        
        [Property("YCoordinate", ColumnType="String")]
        public virtual string YCoordinate {
            get {
                return this._yCoordinate;
            }
            set {
                this._yCoordinate = value;
            }
        }
        
        [Property("CoordinateUnits", ColumnType="String")]
        public virtual string CoordinateUnits {
            get {
                return this._coordinateUnits;
            }
            set {
                this._coordinateUnits = value;
            }
        }
        
        [Property("Comments", ColumnType="String")]
        public virtual string Comments {
            get {
                return this._comments;
            }
            set {
                this._comments = value;
            }
        }
    }
}
