//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJRAtlas.DataWarehouse {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("cdAgency", Schema="dbo")]
    public partial class Agency : DataWarehouseARBase<Agency>
    {
        
        private string _id;
        
        private string _name;
        
        private string _type;
        
        private string _dataRulesInd;
        
        [PrimaryKey(PrimaryKeyType.Native, "AgencyCd", ColumnType="String")]
        public virtual string Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property("Agency", ColumnType="String")]
        public virtual string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        [Property("AgencyType", ColumnType="String")]
        public virtual string Type {
            get {
                return this._type;
            }
            set {
                this._type = value;
            }
        }
        
        [Property("DataRulesInd", ColumnType="String")]
        public virtual string DataRulesInd {
            get {
                return this._dataRulesInd;
            }
            set {
                this._dataRulesInd = value;
            }
        }
    }
    
    [ActiveRecord("auxDataTypes", Schema="dbo", Mutable = false)]
    public partial class DataType : DataWarehouseARBase<DataType> {
        
        private string _dataName;
        
        private string _metadataFileName;
        
        private int _aquaticActivityCd;
        
        private bool _timeSeriesInd;
        
        private bool _map;
        
        private bool _spatialData;
        
        private bool _tabularData;
        
        private bool _graph;
        
        private bool _summaryReport;
        
        private System.DateTime _sSMA_TimeStamp;
        
        private int _dataTypeID;
        
        [Property("DataName", ColumnType="String")]
        public virtual string DataName {
            get {
                return this._dataName;
            }
            set {
                this._dataName = value;
            }
        }
        
        [Property("MetadataFileName", ColumnType="String")]
        public virtual string MetadataFileName {
            get {
                return this._metadataFileName;
            }
            set {
                this._metadataFileName = value;
            }
        }
        
        [Property("AquaticActivityCd", ColumnType="Int32")]
        public virtual int AquaticActivityCd {
            get {
                return this._aquaticActivityCd;
            }
            set {
                this._aquaticActivityCd = value;
            }
        }
        
        [Property("TimeSeriesInd", ColumnType="Boolean")]
        public virtual bool TimeSeriesInd {
            get {
                return this._timeSeriesInd;
            }
            set {
                this._timeSeriesInd = value;
            }
        }
        
        [Property("Map", ColumnType="Boolean")]
        public virtual bool Map {
            get {
                return this._map;
            }
            set {
                this._map = value;
            }
        }
        
        [Property("SpatialData", ColumnType="Boolean")]
        public virtual bool SpatialData {
            get {
                return this._spatialData;
            }
            set {
                this._spatialData = value;
            }
        }
        
        [Property("TabularData", ColumnType="Boolean")]
        public virtual bool TabularData {
            get {
                return this._tabularData;
            }
            set {
                this._tabularData = value;
            }
        }
        
        [Property("Graph", ColumnType="Boolean")]
        public virtual bool Graph {
            get {
                return this._graph;
            }
            set {
                this._graph = value;
            }
        }
        
        [Property("SummaryReport", ColumnType="Boolean")]
        public virtual bool SummaryReport {
            get {
                return this._summaryReport;
            }
            set {
                this._summaryReport = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Native, "DataTypeID", ColumnType="Int32")]
        public virtual int DataTypeID {
            get {
                return this._dataTypeID;
            }
            set {
                this._dataTypeID = value;
            }
        }
    }
}
